name: mindnest
description: MindNest – AI-powered mood & music companion app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons and media


  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

  # Firebase for authentication & messaging
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.3.1

  # Optional: Google Sign-In (if needed in future)
  google_sign_in: ^5.4.2

  #url launch
  url_launcher: ^6.1.10

  youtube_player_flutter: ^9.1.2
  flutter_inappwebview: ^6.0.0
  intl: ^0.20.2
  syncfusion_flutter_charts: ^30.2.5
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

    - assets/images/google.png
    - assets/images/youtube.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
